/*
 * traO-Judge language settings schema
 *
 * Schema only (no endpoint provided)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Languages {
    #[serde(rename = "library", skip_serializing_if = "Option::is_none")]
    pub library: Option<Box<models::LanguagesLibrary>>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<Box<models::LanguagesLanguage>>,
    #[serde(rename = "languages")]
    pub languages: Vec<models::LanguagesLanguage>,
}

impl Languages {
    pub fn new(languages: Vec<models::LanguagesLanguage>) -> Languages {
        Languages {
            library: None,
            language: None,
            languages,
        }
    }
}

