/*
 * traO-Judge language settings schema
 *
 * Schema only (no endpoint provided)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LanguagesLibrary {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl LanguagesLibrary {
    pub fn new(name: String, version: String) -> LanguagesLibrary {
        LanguagesLibrary {
            name,
            version,
        }
    }
}

