/*
 * traO-Judge language settings schema
 *
 * Schema only (no endpoint provided)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Language {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "binName")]
    pub bin_name: String,
    #[serde(rename = "compile")]
    pub compile: String,
    #[serde(rename = "run")]
    pub run: String,
    #[serde(rename = "Libraries", skip_serializing_if = "Option::is_none")]
    pub libraries: Option<Vec<models::Library>>,
}

impl Language {
    pub fn new(name: String, bin_name: String, compile: String, run: String) -> Language {
        Language {
            name,
            bin_name,
            compile,
            run,
            libraries: None,
        }
    }
}

